import { readFileSync, writeFileSync, mkdirSync, rmSync, cpSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {robotsPolicy} from './worker/media-protection.js';

const data = JSON.parse(readFileSync(new URL('./content.json', import.meta.url), 'utf8'));
const out = new URL('./dist/', import.meta.url);
const release = process.env.PUBLIC_RELEASE === 'true';
const siteUrl = process.env.SITE_URL || '';
if (release) {
  const url = new URL(siteUrl);
  if (url.protocol !== 'https:' || url.pathname !== '/' || url.search || url.hash || url.username || url.password || url.hostname === 'localhost') throw new Error('SITE_URL must be the real HTTPS origin');
}
const origin = release ? new URL(siteUrl).origin : '';
rmSync(out, { recursive: true, force: true });
cpSync(new URL('./public/', import.meta.url), out, { recursive: true });
const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e = escapeHtml;
// Sentence breaks are part of the generated HTML, including when JavaScript is off.
const sentenceBreaks = html => html.replace(/<(p|li)(\s[^>]*)?>([\s\S]*?)<\/\1>/g, (whole, tag, attrs, text) => `<${tag}${attrs || ''}>${text.split(/(<[^>]+>)/g).map(part => part.startsWith('<') ? part : part.replace(/。(?!$)/g, '。<br>')).join('')}</${tag}>`);
const nav = [
  ['/', 'HOME'], ['/profile/', 'PROFILE'], ['/music/', 'MUSIC'], ['/guide/', 'FAN GUIDE'], ['/activity/', 'ACTIVITY'], ['/works/', 'WORKS'], ['/links/', 'LINKS']
];
const ext = (label, url, className = 'text-link') => `<a class="${className}" href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(label)}<span aria-hidden="true"> ↗</span></a>`;
const card = (item) => `<article class="story-card"><span class="card-number">${e(item.number)}</span><div><h3>${e(item.title)}</h3><p>${e(item.body)}</p>${item.formUrl ? `<div class="contact-actions"><a class="button-outline" href="${e(item.formUrl)}" target="_blank" rel="noopener noreferrer">相談フォームを開く ↗</a>${ext(item.linkLabel,item.url,'button-outline')}</div>` : ext(item.linkLabel, item.url)}</div></article>`;
const bullets = (items, className = 'bullet-list') => `<ul class="${className}">${items.map(item => `<li>${e(item)}</li>`).join('')}</ul>`;
const songs = [...data.coverSongs.map(x=>({...x,category:'solo'})), ...data.originalSongs.map(x=>({...x,category:'original'})), ...data.collabSongs.map(x=>({...x,category:'collab'}))];
const playerDialog = `<dialog id="song-player" class="song-player" aria-labelledby="player-title"><div class="player-top"><span>NOW PLAYING</span><button type="button" class="player-close" autofocus aria-label="プレイヤーを閉じる">CLOSE ×</button></div><h2 id="player-title"></h2><div class="player-screen"></div><p class="player-help">再生ボタンを押すと曲が流れます。再生できない場合はYouTubeで聴けます。</p><div class="player-bottom"><button type="button" data-player-step="-1">← 前の曲</button><a class="player-external" target="_blank" rel="noopener noreferrer">YouTubeで聴く ↗</a><button type="button" data-player-step="1">次の曲 →</button></div></dialog><script id="song-data" type="application/json">${JSON.stringify(songs).replace(/</g,'\\u003c')}</script>`;
const activeNews = (data.announcements || []).filter(x=>!x.endsAt || new Date(x.endsAt)>=new Date());
const expiredNews = (data.announcements || []).filter(x=>x.endsAt && new Date(x.endsAt)<new Date());
const newsCard = x=>`<a class="news-card" href="${e(x.url)}"${x.url.startsWith('/') ? '' : ' target="_blank" rel="noopener noreferrer"'}><small>${e(x.tag)}</small><strong>${e(x.title)}</strong><p>${e(x.body)}</p><span aria-hidden="true">↗</span></a>`;
const characterDialog = `<dialog class="character-dialog" id="character-dialog" aria-labelledby="character-name"><div class="character-topbar"><span>CHARACTER / ASAHA NEMUI</span><button type="button" class="character-close" autofocus aria-label="キャラクター紹介を閉じる">CLOSE ×</button></div><div class="character-scene"><div class="character-picture"><span class="character-watermark" aria-hidden="true">NEMUI</span><button type="button" class="character-figure" data-kind="full" aria-label="立ち絵をタップして次の画像へ"><img id="character-image" src="${e(data.characterImages[0].src)}" width="${data.characterImages[0].width}" height="${data.characterImages[0].height}" alt="${e(data.characterImages[0].alt)}" loading="lazy"></button><div class="character-picture-nav"><button type="button" data-character-step="-1" aria-label="前の画像へ">←</button><span id="character-image-label" aria-live="polite">01 / ${String(data.characterImages.length).padStart(2,'0')} — ${e(data.characterImages[0].label)}</span><button type="button" data-character-step="1" aria-label="次の画像へ">→</button></div><p class="character-tap-hint">立ち絵をタップして切り替え</p></div><div class="character-bio"><p class="character-caption">歌、言葉、芸術。</p><h2 id="character-name">あさはねむゐ</h2><p class="character-roman">ASAHA NEMUI</p><p class="character-intro">${e(data.intro)}</p><dl class="character-facts"><div><dt>BIRTHDAY</dt><dd>7月13日</dd></div><div><dt>FROM</dt><dd>京都</dd></div><div><dt>IMAGE COLOR</dt><dd><span class="aurora-swatch" aria-hidden="true"></span>オーロラ</dd></div><div><dt>FAN MARK</dt><dd>🍣💤</dd></div><div><dt>FAN NAME</dt><dd>ラブリーチャーミング / LC</dd></div></dl><p class="character-note" id="character-note">${e(data.characterImages[0].description)}</p><div class="character-select" aria-label="プロフィール画像を選ぶ">${data.characterImages.map((asset,i)=>`<button type="button" data-character-index="${i}" aria-label="${e(asset.label)}を表示" aria-pressed="${i===0}"><img src="${e(asset.poster || asset.src)}" alt="" loading="lazy"><span>0${i+1}</span></button>`).join('')}</div><p class="character-selection-label">${data.characterImages.length} VISUALS / 衣装と表情を選んでください</p><a href="/profile/" class="character-profile-link">プロフィールを読む ↗</a></div></div></dialog>`;
const seo = (key,title,description) => `${!release || key === '/404/' || key === '/backstage/' ? '<meta name="robots" content="noindex, nofollow">' : `<link rel="canonical" href="${e(origin+key)}"><meta property="og:url" content="${e(origin+key)}">`}<meta property="og:type" content="website"><meta property="og:locale" content="ja_JP"><meta property="og:site_name" content="${e(data.name)}"><meta property="og:title" content="${e(title+' | '+data.name)}"><meta property="og:description" content="${e(description)}">${release ? `<meta property="og:image" content="${e(origin)}/assets/og-cover-v2.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="あさはねむゐ OFFICIAL SITE"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="${e(origin)}/assets/og-cover-v2.png">` : ''}`;
const layout = (key, title, description, body) => `<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#17142c"><title>${e(title)} | ${e(data.name)}</title><meta name="description" content="${e(description)}">${seo(key,title,description)}<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='15' fill='%235b36b1'/%3E%3Ctext x='32' y='47' text-anchor='middle' fill='%23ffffff' font-family='sans-serif' font-weight='700' font-size='46'%3Eゐ%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/style.css"><script src="/startup.js"></script></head>
<body${key==='/music/'?' class="music-page"':''}><div class="site-shell" id="top"><header class="site-header"><a class="brand" href="/" aria-label="あさはねむゐ ホーム"><span class="brand-mark">ゐ</span><span>${e(data.name)}<small>ASAHA NEMUI</small></span></a><nav class="desktop-nav" aria-label="メインナビゲーション">${nav.map(([href,label],index)=>`<a href="${href}" data-chapter="${String(index).padStart(2,'0')}" ${key===href?'aria-current="page"':''}>${label}</a>`).join('')}</nav><button class="menu-button" type="button" aria-expanded="false" aria-controls="mobile-nav" aria-label="メニューを開く"><span></span><span></span></button></header><nav class="mobile-nav" id="mobile-nav" aria-label="モバイルナビゲーション" hidden>${nav.map(([href,label])=>`<a href="${href}" ${key===href?'aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="reading-progress" aria-hidden="true"></div><main>${['/guide/','/works/'].includes(key) ? sentenceBreaks(body) : body}</main><footer class="site-footer"><button class="secret-star" type="button" aria-label="小さな星に触れる">✦</button><span class="footer-name">${e(data.name)}</span><div class="footer-links"><nav class="footer-nav" aria-label="フッターナビゲーション">${nav.map(([href,label])=>`<a href="${href}" ${key===href?'aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="footer-utility"><a href="/privacy/">PRIVACY</a>${ext('YouTube', 'https://www.youtube.com/@nemui-asaha', 'footer-external')}${ext('X', 'https://x.com/asa_nemui_zzz', 'footer-external')}</div></div><small>© ${new Date().getUTCFullYear()} ASAHA NEMUI</small></footer></div><a class="back-to-top" href="#top" aria-label="ページの上部へ戻る"><span aria-hidden="true">↑</span><small>TOP</small></a>${key==='/'||key==='/profile/'?characterDialog+`<script type="application/json" id="character-assets">${JSON.stringify(data.characterImages).replace(/</g, '\\u003c')}</script>`:''}${key==='/'||key==='/music/'?playerDialog:''}<script src="/site.js" defer></script><script src="/capture-mode.js" defer></script></body></html>`;

const officialVisual = `<button class="official-visual character-trigger" type="button" data-character-open data-kind="portrait" aria-haspopup="dialog" aria-controls="character-dialog" aria-label="あさはねむゐのキャラクター紹介を開く"><span class="character-trigger-word" aria-hidden="true">NEMUI</span><img src="/assets/profile-character.png" alt="通常衣装のあさはねむゐのバストアップ" width="1468" height="2048"><span class="character-open-label">CHARACTER PROFILE <b>＋</b><small>タップして、もっと見る</small></span></button>`;
const headingParts = title => ({'あさはねむゐのこと':['あさはねむゐ','のこと'],'応援してくれるみんなへ':['応援してくれる','みんなへ']}[title] || [title]).map(part => `<span class="heading-phrase">${e(part)}</span>`).join('<wbr>');
const innerIntro = (eyebrow, title, lead) => `<section class="inner-hero"><p class="kicker">${e(eyebrow)}</p><h1>${headingParts(title)}</h1><p class="inner-lead">${e(lead)}</p></section>`;
const profile = `${innerIntro('01 / PROFILE','あさはねむゐのこと','歌って喋る、関西弁のお兄ちゃんVTuber。')}<section class="section profile-layout"><div class="profile-statement">${officialVisual}<p class="visual-credit">衣装・表情をタップで切り替えられます。</p></div><div class="profile-facts"><h2 class="eyebrow-heading">PROFILE NOTES</h2><p>${e(data.intro)}</p>${data.facts.map(({label,value})=>`<div class="fact"><span>${e(label)}</span><strong>${label==='イメージカラー'?'<span class="aurora-swatch" aria-hidden="true"></span>':''}${e(value)}</strong></div>`).join('')}</div></section><section class="section profile-kv"><div class="profile-kv-copy"><p class="kicker">KEY VISUAL</p><span class="profile-kv-count" aria-live="polite">01 / 02</span></div><button class="profile-kv-stage" type="button" aria-label="次のキービジュアルを見る"><img class="kv-first" src="/assets/kv-pose.png" alt="あさはねむゐの笑顔のキービジュアル" width="2018" height="2048" loading="lazy"><img class="kv-second" src="/assets/kv-pose-close.png" alt="あさはねむゐの微笑むキービジュアル" width="2048" height="1936" loading="lazy"><span class="kv-stage-hint" aria-hidden="true">TAP</span></button></section><section class="section band-section"><p class="kicker">WHAT I LOVE</p><p class="large-line"><span class="love-line"><span class="love-phrase">歌、映画、舞台、</span><wbr><span class="love-phrase">ファッション。</span></span><span class="love-line"><span class="love-phrase">お寿司なら、</span><wbr><em class="love-phrase">週8でもいい。</em></span></p></section><section class="section profile-details"><div class="detail-block"><p class="kicker">DOING</p><h2>いまやっていること</h2>${bullets(data.about.activities)}<div class="showcase-link">${ext(data.about.showcase.label + " / 詳細", data.about.showcase.url)}</div></div><div class="detail-block"><p class="kicker">FAVORITES</p><h2>好きなこと</h2>${bullets(data.about.favorites)}</div><div class="detail-block"><p class="kicker">MORE ABOUT ME</p><h2>もう少しだけ</h2>${bullets(data.about.personal)}</div></section><section class="section play-list"><div><p class="kicker">MYSTERY & TRPG</p><h2>通過した作品</h2><p>配信した作品もあります。思い出したら少しずつ更新します。</p>${ext('配信リストを見る','https://youtube.com/playlist?list=PLWDQOZM9jgrAUhRt4fmjLPZK_lb2bLr7B')}</div><div><h3>マーダーミステリー</h3>${bullets(data.about.mystery)}<h3>TRPG</h3>${bullets(data.about.trpg)}</div></section>`;
const guide = `${innerIntro('03 / FAN GUIDE','応援してくれるみんなへ','タグや二次創作、切り抜きについての案内です。')}<section class="section guide-index"><p class="kicker">FAN TAGS</p><h2>タグを使うとき</h2><div class="tag-grid">${data.tags.map(item=>`<div class="tag-card"><span>${e(item.label)}</span><strong>${e(item.value)}</strong>${item.detail?`<p>${e(item.detail)}</p>`:''}</div>`).join('')}</div></section><section class="section guide-content"><p class="kicker">GUIDELINES</p><h2>活動のガイドライン</h2><div class="guide-sections">${data.guidelines.map((item,i)=>`<article id="guide-${i+1}" class="guide-section"><span class="card-number">0${i+1}</span><div><h3>${e(item.title)}</h3>${item.paragraphs.map(p=>`<p>${e(p)}</p>`).join('')}${item.points.length?bullets(item.points):''}</div></article>`).join('')}</div></section><section class="section fan-art-brief"><p class="kicker">FAN ART REQUESTS</p><h2>イラストを依頼してくれる方へ</h2><p class="wide-copy">Skebなどで依頼していただくのは問題ないです。クリエイターの方には、本人の許可があることと、活動で使用する可能性があることをお伝えください。</p><div class="brief-grid"><div><h3>見た目の特徴</h3>${bullets(data.fanArtBrief.features)}</div><div><h3>想定する用途</h3>${bullets(data.fanArtBrief.uses)}</div><div><h3>依頼時の補足</h3>${bullets(data.fanArtBrief.notes)}</div></div>${ext('イラストレーター様',data.fanArtBrief.illustrators)}</section>`;
const projectCards = `<div class="project-grid">${data.projects.map((p,i)=>`<a class="project-card project-card-${i+1}" href="/projects/${e(p.slug)}/"><span class="kicker">PROJECT / 0${i+1}</span><span class="project-art-word" aria-hidden="true">${e(p.english)}</span><div><h3>${e(p.title)}</h3><p>${e(p.summary)}</p><span class="project-enter">特設ページへ <b aria-hidden="true">↗</b></span></div></a>`).join('')}</div>`;
const projectIndex = `${innerIntro('PROJECTS','企画の特設ページ','ファッションショー、showcase.A。企画の世界と、その記録。')}<section class="section">${projectCards}</section>`;
const safeProjectUrl = value => {const u=new URL(value,'https://asaha-nemui.com');if(u.protocol!=='https:'||u.username||u.password)throw Error('Invalid project URL');return e(value);};
const projectBody = p => `${innerIntro(p.english,p.title,p.summary)}<section class="section project-intro"><div><p class="kicker">ABOUT THE PROJECT</p>${p.description.map(text=>`<p>${e(text)}</p>`).join('')}</div><div class="project-link-list">${p.links.map(link=>ext(link.label,link.url)).join('')}</div></section>${p.photos.length?`<section class="section"><p class="kicker">GALLERY</p><h2>写真とビジュアル</h2><div class="project-photos">${p.photos.map(photo=>`<figure><a href="${safeProjectUrl(photo.src)}" target="_blank" rel="noopener noreferrer" aria-label="${e(photo.alt)}を大きく見る"><img src="${safeProjectUrl(photo.src)}" alt="${e(photo.alt)}" loading="lazy"></a><figcaption>${e(photo.caption||'')}${photo.credit?`<small>${e(photo.credit)}</small>`:''}</figcaption></figure>`).join('')}</div></section>`:''}${p.videos.length?`<section class="section"><p class="kicker">FILMS</p><h2>動画で振り返る</h2><div class="project-videos">${p.videos.map(video=>{if(!/^[A-Za-z0-9_-]{11}$/.test(video.videoId))throw Error('Invalid project video');return `<a href="https://www.youtube.com/watch?v=${video.videoId}" target="_blank" rel="noopener noreferrer"><img src="https://i.ytimg.com/vi/${video.videoId}/hqdefault.jpg" alt="" loading="lazy"><h3>${e(video.title)}</h3><span>WATCH ON YOUTUBE ↗</span></a>`;}).join('')}</div></section>`:''}${p.records.length?`<section class="section"><p class="kicker">ARCHIVE</p><h2>開催の記録</h2><ol class="project-records">${p.records.map(record=>`<li><span>${e(record.date)}</span><div><h3>${e(record.title)}</h3><p>${e(record.body)}</p></div></li>`).join('')}</ol></section>`:''}<section class="section project-return"><a class="text-link" href="/projects/">← 企画一覧へ</a><a class="text-link" href="/activity/">活動のいろいろへ ↗</a></section>`;

const activity = `${innerIntro('04 / ACTIVITY','活動のいろいろ','企画、イベント、グッズ。新しい情報は随時ここにも追加していきます。')}<section class="section"><p class="kicker">PROJECTS</p><h2>企画の特設ページ</h2>${projectCards}</section><section class="section story-list">${data.activity.map(card).join('')}</section><section class="section related-links"><a href="/works/"><span>掲載・コラボの記録</span><strong>活動実績を見る ↗</strong></a><a href="/guide/"><span>ファンアート・切り抜き</span><strong>ガイドラインを見る ↗</strong></a></section>`;
const works = `${innerIntro('05 / WORKS','活動の記録','企業案件・メディア掲載・広告など、これまでの主な実績。')}<section class="section record-list">${expiredNews.length?`<div class="news-archive"><h2>過去のお知らせ</h2>${expiredNews.map(newsCard).join('')}</div>`:''}${data.record.map(group=>`<div class="record-year"><h2>${e(group.year)}</h2>${bullets(group.items,'record-items')}</div>`).join('')}</section><section class="section contact-section"><p class="kicker">CONTACT</p><h2>ご連絡について</h2><p class="contact-lead">ご相談・お問い合わせは相談フォーム、またはXのDMへお願いします。XのDMをご利用の場合は、通知を見落とさないよう、フォローのうえご連絡ください。</p><div class="contact-grid"><article><span>01 / COLLABORATION</span><h3>コラボのご相談</h3><p>歌ってみたや歌枠リレー、雑談、ゲーム、マダミス・TRPGなど、一緒に楽しめるお誘いを歓迎しています。</p><p>「こんなこと一緒にやってみない？」くらいの気軽なご相談もぜひ。まずはやってみたいことを聞かせてください。</p></article><article><span>02 / BUSINESS</span><h3>企業様へ</h3><p>出演・歌唱、制作、タイアップなど、お仕事のご相談を受け付けています。企画内容、希望時期、ご予算など、わかる範囲でお知らせください。</p><p>活動内容をご確認のうえ、ご相談ください。アプリなどへの勧誘は基本的にお断りしています。</p></article></div><div class="contact-actions"><a class="button-outline" href="/projects/showcase-a/contact/" target="_blank" rel="noopener noreferrer">相談フォームを開く ↗</a>${ext('XのDMへ','https://x.com/asa_nemui_zzz','button-outline')}</div></section>`;
const groups = [...new Set(data.links.map(x=>x.group))];
const links = `${innerIntro('06 / LINKS','リンク','動画、告知、ショップへの入口をまとめました。')}<section class="section link-groups">${groups.map(group=>`<div class="link-group"><h2>${e(group)}</h2>${data.links.filter(x=>x.group===group).map(x=>`<a class="link-row" href="${e(x.url)}" target="_blank" rel="noopener noreferrer"><span><strong>${e(x.label)}</strong><small>${e(x.detail)}</small></span><b aria-hidden="true">↗</b></a>`).join('')}</div>`).join('')}</section>`;

const songCard = (song, index, duplicate = false) => {
  const id = song.videoId;
  if (!/^[A-Za-z0-9_-]{11}$/.test(id)) throw new Error('Invalid video ID');
  return `<a class="song-frame song-frame-${index + 1}" style="--float-delay:-${(index % 7) * .8}s;--frame-lean:${index % 2 ? 3 : -3}deg" href="https://www.youtube.com/watch?v=${id}" target="_blank" rel="noopener noreferrer" ${duplicate ? 'tabindex="-1"' : ''} aria-label="${e(song.title)} の動画をYouTubeで見る"><span class="song-visual"><img src="https://i.ytimg.com/vi/${id}/hqdefault.jpg" alt="" loading="lazy" width="480" height="360"><span class="song-play" aria-hidden="true">↗</span><span class="song-frame-label">ASAHA NEMUI / ${String(index + 1).padStart(2, '0')}</span></span><span class="song-meta"><span class="song-type">${e(song.type)}</span><strong>${e(song.title)}</strong><span class="song-artist">${e(song.artist)}</span>${song.collaborators?.length ? `<span class="song-collaborators">with ${e(song.collaborators.join("・"))}${song.group ? ` <span class="song-group">/ ${e(song.group)}</span>` : ""}</span>` : ""}</span></a>`;
};
const movingGallery = (songs, title, kicker, id, note = '') => `<section class="music-showcase" aria-labelledby="${id}"><div class="music-heading"><div><p class="kicker">${kicker}</p><h2 id="${id}">${title}<small class="song-count">${songs.length} TRACKS</small></h2></div><p>${note || 'フレームを選ぶとプレイヤーが開きます。'}</p></div><div class="song-viewport"><div class="song-track"><div class="song-set">${songs.map((song, i) => songCard(song, i)).join('')}</div><div class="song-set" aria-hidden="true">${songs.map((song, i) => songCard(song, i, true)).join('')}</div></div></div><div class="music-bottom"><div class="gallery-controls"><button type="button" class="gallery-shuffle" aria-label="曲の順番をシャッフル">SHUFFLE ↝</button><button type="button" class="gallery-prev" aria-label="前の曲へ">←</button><button type="button" class="gallery-toggle" aria-pressed="false">流れを止める</button><button type="button" class="gallery-next" aria-label="次の曲へ">→</button></div><a href="/music/#song-library">一覧で見る / ALL MUSIC <span aria-hidden="true">↗</span></a></div></section>`;
const songGallery = movingGallery([...data.coverSongs, ...data.originalSongs], '歌', 'SOLO SONGS / ソロ楽曲', 'music-showcase-title');
const originalPick = `<section class="original-section"><div class="original-heading"><p class="kicker">ORIGINAL SONGS / オリジナル曲</p><h2>この声から、生まれた曲。</h2></div><div class="original-grid">${data.originalSongs.map((song,i)=>songCard(song,i)).join('')}</div></section>`;
const latestCover = data.coverSongs[0];
const latestDate = latestCover.publishedAt ? new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(latestCover.publishedAt)).replaceAll('/','.') : '';
const monthlyFeature = `<section class="monthly-feature" aria-labelledby="monthly-title"><div class="monthly-copy"><span class="monthly-index">MONTHLY RELEASE / EVERY 13TH</span><p class="kicker" id="monthly-label">最新の歌ってみた</p><h2 id="monthly-title">${e(data.coverSongs[0].title)}</h2><p>${e(data.coverSongs[0].artist)} の楽曲をカバー。<span class="monthly-release-note">毎月13日に新しい歌を届けています。</span></p><span class="feature-date">${e(latestDate)} / NEW COVER</span>${ext('MVを見る',`https://www.youtube.com/watch?v=${data.coverSongs[0].videoId}`,'button-primary')}</div><a class="monthly-art" href="https://www.youtube.com/watch?v=${data.coverSongs[0].videoId}" target="_blank" rel="noopener noreferrer" aria-label="最新の歌ってみた ${e(data.coverSongs[0].title)} のMVを見る"><img src="https://i.ytimg.com/vi/${data.coverSongs[0].videoId}/maxresdefault.jpg" alt="" data-fallback-src="https://i.ytimg.com/vi/${data.coverSongs[0].videoId}/hqdefault.jpg" width="1280" height="720"><span aria-hidden="true">PLAY MV ↗</span></a></section>`;
const dailySong = `<section id="daily-pick" class="section daily-song" aria-labelledby="daily-song-title"><div class="daily-copy"><p class="kicker">DAILY PICK / MUSIC OMikuji</p><h2 id="daily-song-title">本日の一曲</h2><p>今日は、どの歌に出会う？</p><small>毎日ひとつ。日付が変わったら、またどうぞ。</small></div><div class="daily-draw"><button type="button" class="daily-draw-button" aria-controls="daily-result"><span aria-hidden="true">✦</span><strong>今日の一曲を引く</strong><small>TAP TO DISCOVER</small></button><div id="daily-result" hidden aria-live="polite"></div><noscript><a href="#song-library">全曲一覧から歌を選ぶ ↗</a></noscript></div></section><section class="section song-collection"><details><summary>出会った曲のコレクション <span id="collection-count">0曲</span></summary><p class="collection-note">引いた日と一緒に、このブラウザに保存されます。別の端末とは共有されず、ブラウザのデータを消すとリセットされます。</p><div id="collection-list"></div><p id="collection-empty">最初の一曲を引くと、ここに記録されます。</p></details></section>`;
const newsSection = `<section class="section home-news"><div class="section-title"><div><p class="kicker">PICK UP</p><h2>企画・グッズをチェック</h2></div><a href="/activity/">活動のいろいろ ↗</a></div><div class="news-grid">${activeNews.filter(item => !item.url.includes(data.coverSongs[0].videoId)).slice(0,3).map(newsCard).join('')}</div></section>`;
const songLibrary = `<section class="section song-library" id="song-library"><p class="kicker">ALL TRACKS</p><h2>曲を探す</h2><label class="song-search">曲名・アーティスト名<input type="search" id="song-search" placeholder="曲名や名前を入力" autocomplete="off"></label><div class="song-filters" aria-label="楽曲の種類">${[['all','すべて'],['solo','ソロ'],['collab','コラボ'],['original','オリジナル']].map(([value,label])=>`<button type="button" data-song-filter="${value}" aria-pressed="${value==='all'}">${label}</button>`).join('')}</div><p id="song-results" role="status">${songs.length}曲</p><div class="library-grid">${songs.map((song,i)=>`<div class="library-item" data-category="${song.category}" data-search="${e([song.title,song.artist,...(song.collaborators || []),song.group || ''].join(' '))}">${songCard(song,i)}</div>`).join('')}</div><p class="library-empty" hidden>該当する曲がありません。別の言葉で探してみてください。</p><noscript>検索と絞り込みにはJavaScriptが必要です。全曲は下の一覧から選べます。</noscript></section>`;
const chapters = [
  ['/profile/', '01', 'PROFILE', 'あさはねむゐのこと', '好きなこと、夢、これまでのこと。'],
  ['/music/', '02', 'MUSIC', '歌を聴く', '歌ってみた、オリジナル曲、コラボ曲。'],
  ['/guide/', '03', 'FAN GUIDE', '応援してくれるみんなへ', 'タグ、二次創作、切り抜きの案内。'],
  ['/activity/', '04', 'ACTIVITY', '活動のいろいろ', '企画、イベント、グッズ。'],
  ['/works/', '05', 'WORKS', '活動の記録', '掲載、コラボ、広告。'],
  ['/links/', '06', 'LINKS', 'リンク一覧', 'SNS、ショップ、お問い合わせ。']
];
const homeV2 = `<section class="cinema-hero"><div class="hero-grain" aria-hidden="true"></div><div class="kinetic-word" aria-hidden="true">UNPREDICTABLE.</div><div class="hero-kicker">INDEPENDENT VTUBER <span>✦</span> KYOTO, JAPAN</div><div class="cinema-grid"><div class="cinema-copy"><p class="cinema-overline">歌、言葉、芸術。</p><h1><span class="jp-line"><span class="name-char">あ</span><span class="name-char">さ</span><span class="name-char">は</span></span><span class="jp-line"><span class="name-char">ね</span><span class="name-char">む</span><span class="name-char">ゐ</span><span class="accent-dot">.</span></span></h1><p class="cinema-roman">ASAHA NEMUI / 07.13</p><p class="cinema-lead">${e(data.intro).replace(/いつだってねむい。$/, '<span class="hero-sleepy-note">いつだってねむい。</span>')}</p><div class="cinema-actions"><a href="/music/">歌を聴く <span aria-hidden="true">↗</span></a>${ext('配信を見る','https://www.youtube.com/@nemui-asaha/streams','hero-live-action')}</div></div><div class="cinema-art"><span class="visual-ribbon">🍣💤 / ALWAYS SLEEPY</span>${officialVisual}<span class="art-side">OFFICIAL PROFILE / ASAHA NEMUI</span></div></div><div class="hero-ticker" aria-hidden="true"><div class="ticker-track"><span>ASAHA NEMUI　✦　SINGER　✦　TALKER　✦　ASAHA NEMUI　✦　SINGER　✦　TALKER　✦　ASAHA NEMUI　✦　SINGER　✦　TALKER　✦　ASAHA NEMUI　✦　SINGER　✦　TALKER　✦　ASAHA NEMUI　✦　SINGER　✦　TALKER　✦　</span><span>ASAHA NEMUI　✦　SINGER　✦　TALKER　✦　ASAHA NEMUI　✦　SINGER　✦　TALKER　✦　ASAHA NEMUI　✦　SINGER　✦　TALKER　✦　ASAHA NEMUI　✦　SINGER　✦　TALKER　✦　ASAHA NEMUI　✦　SINGER　✦　TALKER　✦　</span></div></div></section>
${monthlyFeature}<section class="home-live section" aria-labelledby="home-live-title"><div class="home-live-copy"><p class="kicker">TALK / LIVE</p><h2 id="home-live-title">よく喋って、<br>よく笑う。</h2><p>歌の合間にも、関西弁のおしゃべりを。映画やゲームの話、日々のあれこれまで。雑談と歌配信で、あさはねむゐの声に会いに来てください。</p><div class="home-live-topics" aria-label="おしゃべりの話題"><span>映画</span><span>ゲーム</span><span>日々のこと</span></div></div><div class="home-live-guide"><p class="kicker">FIRST VISIT / 初めての方へ</p><h3>配信の入り口</h3><ol><li><strong>まずは、気になるアーカイブから。</strong><p>配信一覧でタイトルを選んで、歌もおしゃべりも楽しめます。</p></li><li><strong>次の配信を見つける。</strong><p>YouTubeの配信一覧で待機所を、Xで最新の告知をチェック。</p></li><li><strong><a class="home-live-music-link" href="/music/#song-library">歌ってみたを聴く <span aria-hidden="true">↗</span></a></strong><p>毎月13日に公開するカバーを、MUSICページでまとめて楽しめます。</p></li></ol><div class="home-live-guide-links">${ext('YouTubeで配信を見る','https://www.youtube.com/@nemui-asaha/streams')}${ext('Xで告知を見る',data.links.find(link => link.label === 'X').url)}</div></div></section>${newsSection}<section class="editorial-intro"><div class="editorial-labels"><span class="intro-index">ABOUT / 001</span><span class="kicker">HELLO, I'M NEMUI.</span></div><div class="editorial-body"><h2><em>歌、言葉、芸術。</em></h2><p>${e(data.homeAbout).replaceAll('。', '。<br>').replace(/<br>$/, '')}</p></div><a href="/profile/" aria-label="プロフィールを見る">↗</a></section>
<section class="logo-motion" aria-label="あさはねむゐのロゴアニメーション"><div class="logo-motion-heading"><span>ASAHA NEMUI</span><span>LOGO</span></div><video autoplay muted loop playsinline preload="metadata" controlslist="nodownload nofullscreen noremoteplayback" disablepictureinpicture disableremoteplayback draggable="false" poster="/assets/logo-motion-poster.jpg" aria-label="あさはねむゐのロゴが現れるアニメーション"><source src="/assets/logo-motion-loop.mp4" type="video/mp4"></video></section>
${songGallery}
<section class="chapter-section"><div class="chapter-top"><p class="kicker">CONTENTS / サイト案内</p><h2>サイト案内</h2><p>知りたいことから、選んでください。</p></div><div class="chapter-list">${chapters.map(([href,num,en,ja,desc])=>`<a href="${href}" class="chapter-row"><span class="chapter-num">${num}</span><span class="chapter-title"><small>${en}</small><strong>${ja}</strong></span><span class="chapter-desc">${desc}</span><span class="chapter-arrow" aria-hidden="true">↗</span></a>`).join('')}</div></section>`;
const musicV2 = `${innerIntro('02 / MUSIC','歌','毎月13日に歌ってみたを公開。オリジナル曲、コラボ曲もここから。')}${monthlyFeature}${dailySong}<div class="library-jump"><a class="button-outline" href="#song-library">全曲一覧・検索 ↓</a></div>${originalPick}${songGallery}${movingGallery(data.collabSongs,'一緒に。','COLLABORATION / コラボ曲','collab-title','共演から生まれた曲を、別の流れで。')}${songLibrary}<section class="section story-list">${data.music.map(card).join('')}</section><section class="section closing-note"><span class="kicker">ON YOUTUBE</span><h2>もっと聴きたくなったら。</h2>${ext('歌ってみたの再生リストへ','https://www.youtube.com/playlist?list=PLWDQOZM9jgrCazo9MdcDKwB6UZWd9NSiP','button-primary')}</section>`;

const privacy = `${innerIntro('PRIVACY','プライバシーについて','このサイトの保存データと外部サービスについて。')}<section class="section guide-content"><h2>このブラウザに保存するもの</h2><p>本日の一曲とコレクションは、曲のIDや日付をブラウザ内に保存します。端末間では同期されません。ブラウザのサイトデータを消すと削除できます。画面転換のため、一時的な情報もブラウザ内に保存します。</p><h2>外部サービスへの通信</h2><p>サイトはCloudflareから配信されます。画像の表示時にはYouTubeのサムネイル配信先、フォントの表示時にはGoogle Fontsへの通信が発生します。楽曲のプレイヤーを開くとYouTubeのプライバシー強化モードを利用した埋め込みプレイヤーを読み込みます。各サービスにはIPアドレスなど通信に必要な情報が送信され、各社のポリシーに従って処理されます。</p><p>Xへのシェアは投稿画面を開く機能です。自動で投稿することはありません。このサイトには一般向けの会員登録はありません。</p><h2>ご相談・お問い合わせフォーム</h2><p>フォームに入力された活動者名・団体名、活動先、活動内容、相談内容、送信者名、連絡先を、ご相談・ご依頼の検討と必要な連絡のために利用します。回答はCloudflareの専用保存領域に保存し、管理者のみが確認します。公開ページや公開用ファイルには掲載しません。管理者への新着メール通知にResendを利用し、相談の種類・受付日時・受付番号を通知します。相談本文や連絡先は通知メールに含めません。</p><p>不正な連続送信を防ぐため、IPアドレスを復元できない形に変換した識別情報を短時間保存します。管理画面のログイン状態を維持するCookieの有効期間は8時間です。フォームの回答は受付から1年が経過すると自動的に削除します。それより前でも、対応が終わり不要になったものは順次削除します。フォームの内容の訂正・削除を希望される場合は、受付番号を添えて活動ページの窓口へご連絡ください。</p><h2>お問い合わせ</h2><p>掲載内容についてのご連絡は、活動ページに記載した窓口をご利用ください。</p><a class="text-link" href="/activity/">連絡先を見る ↗</a></section>`;
const pages = [
  ['/projects/', '企画の特設ページ', 'ファッションショーとshowcase.Aの特設ページ。', projectIndex],
  ...data.projects.map(p=>['/projects/'+p.slug+'/',p.title,p.summary,projectBody(p)]),
  ['/privacy/', 'プライバシー', 'サイトの保存データと外部サービスについて。', privacy],
  ['/', 'OFFICIAL SITE', data.homeAbout, homeV2],
  ['/profile/', 'プロフィール', 'あさはねむゐのプロフィール。京都出身、関西弁の個人勢VTuber。', profile],
  ['/music/', '歌と配信', 'あさはねむゐの歌ってみた、雑談配信、ゲーム実況。', musicV2],
  ['/guide/', '応援とガイドライン', 'あさはねむゐのファンタグ、二次創作、切り抜きのガイドライン。', guide],
  ['/activity/', '活動とグッズ', 'あさはねむゐの企画、イベント、グッズ、お問い合わせ。', activity],
  ['/works/', '活動実績', 'あさはねむゐの企業案件、メディア掲載、広告などの記録。', works],
  ['/links/', 'リンク', 'あさはねむゐのYouTube、X、ショップなど。', links]
];
for (const [route,title,description,body] of pages) {
  const dir = join(fileURLToPath(out), route);
  mkdirSync(dir, { recursive:true });
  writeFileSync(join(dir,'index.html'), layout(route,title,description,body));
}

const backstage = `<section class="backstage-page"><div class="backstage-grid" aria-hidden="true"></div><p class="kicker">BACKSTAGE / 00</p><h1>LIGHTS ON.</h1><p class="backstage-sub">ASAHA NEMUI / SECRET ROOM</p><a class="button-outline" href="/">RETURN TO SITE ↗</a></section>`;
{
  const route = '/backstage/';
  const dir = join(fileURLToPath(out), route);
  mkdirSync(dir, { recursive:true });
  writeFileSync(join(dir,'index.html'), layout(route,'BACKSTAGE','Hidden backstage page.',backstage));
}

writeFileSync(join(fileURLToPath(out),'404.html'), layout('/404/','ページが見つかりません','指定されたページは見つかりませんでした。', '<section class="section"><h1>ページが見つかりません。</h1><a href="/">HOMEへ戻る</a></section>'));
writeFileSync(join(fileURLToPath(out),'robots.txt'), robotsPolicy(origin,release));
if (release) writeFileSync(join(fileURLToPath(out),'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(([route])=>`<url><loc>${e(origin+route)}</loc></url>`).join('')}</urlset>`);
const csp = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://i.ytimg.com; media-src 'self'; frame-src https://www.youtube-nocookie.com; connect-src 'self'; object-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; upgrade-insecure-requests";
writeFileSync(join(fileURLToPath(out),'_headers'), `/*\n  Content-Signal: search=yes, ai-train=no\n  Content-Security-Policy: ${csp}\n  X-Content-Type-Options: nosniff\n  X-Frame-Options: DENY\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Strict-Transport-Security: max-age=31536000\n${release ? '' : '  X-Robots-Tag: noindex, nofollow\n'}`);
console.log(`Built ${pages.length} pages (${release ? 'production' : 'private preparation / noindex'}).`);
